// Seed data for Accessible Rostov - real places in Rostov-on-Don with accessibility info

export const places = [
  {
    name: "ТРЦ \"Горизонт\"",
    description: "Крупный торговый центр с полной доступностью для маломобильных граждан. Пандусы на всех входах, лифты, широкие проходы, парковка для инвалидов.",
    category: "shop",
    address: "пр. Михаила Нагибина, 32/2, Ростов-на-Дону",
    latitude: 47.2362,
    longitude: 39.7127,
    phone: "+7 (863) 303-10-20",
    website: "https://gorizont-rostov.ru",
    images: "[]",
    accessibility_tags: "ramp,wide_door,elevator,parking_disabled,tactile_tiles",
    disability_types: "wheelchair,visually_impaired,hearing_impaired,limited_mobility,elderly,stroller",
    rating: 4.5,
    reviews_count: 23
  },
  {
    name: "Кинотеатр \"Большой\"",
    description: "Современный кинотеатр с доступными залами, субтитрами на некоторых сеансах и пандусом у входа. Есть вибросигнальные устройства для слабослышащих.",
    category: "cinema",
    address: "ул. Красноармейская, 176, Ростов-на-Дону",
    latitude: 47.2241,
    longitude: 39.7183,
    phone: "+7 (863) 263-38-98",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,wide_door,subtitles,vibro_signal,parking_disabled",
    disability_types: "wheelchair,hearing_impaired,limited_mobility,elderly,stroller",
    rating: 4.2,
    reviews_count: 15
  },
  {
    name: "Поликлиника N1 Кировского района",
    description: "Городская поликлиника с безбарьерной средой. Тактильная навигация, пандусы, кнопки вызова персонала.",
    category: "clinic",
    address: "пр. Ворошиловский, 105, Ростов-на-Дону",
    latitude: 47.2316,
    longitude: 39.7189,
    phone: "+7 (863) 232-01-01",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,elevator,tactile_tiles,audio_guide,handrails,braille",
    disability_types: "wheelchair,visually_impaired,hearing_impaired,limited_mobility,cognitive,elderly",
    rating: 3.8,
    reviews_count: 31
  },
  {
    name: "Кафе \"Тихий Дон\"",
    description: "Уютное кафе с доступным входом и удобным расположением столиков для колясок. Меню доступно шрифтом Брайля.",
    category: "cafe",
    address: "ул. Большая Садовая, 47, Ростов-на-Дону",
    latitude: 47.2271,
    longitude: 39.7463,
    phone: "+7 (863) 250-55-55",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,wide_door,braille,low_floor_transport",
    disability_types: "wheelchair,visually_impaired,limited_mobility,elderly,stroller",
    rating: 4.6,
    reviews_count: 12
  },
  {
    name: "Ростовский музыкальный театр",
    description: "Театр с доступной средой: пандусы, лифт, специальные места для колясочников, индукционные петли для слабослышащих.",
    category: "theater",
    address: "ул. Большая Садовая, 134, Ростов-на-Дону",
    latitude: 47.2283,
    longitude: 39.7439,
    phone: "+7 (863) 264-04-07",
    website: "https://muzkom.ru",
    images: "[]",
    accessibility_tags: "ramp,elevator,wide_door,vibro_signal,subtitles,parking_disabled",
    disability_types: "wheelchair,hearing_impaired,limited_mobility,elderly,stroller",
    rating: 4.7,
    reviews_count: 19
  },
  {
    name: "Парк Горького",
    description: "Центральный парк с доступными дорожками, скамейками, тактильной навигацией и зонами отдыха.",
    category: "park",
    address: "ул. Большая Садовая, 45, Ростов-на-Дону",
    latitude: 47.2264,
    longitude: 39.7478,
    phone: "",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,tactile_tiles,bench,rest_area,simple_navigation,wide_door",
    disability_types: "wheelchair,visually_impaired,limited_mobility,cognitive,elderly,stroller",
    rating: 4.4,
    reviews_count: 28
  },
  {
    name: "Аптека \"Социальная\"",
    description: "Аптека с пандусом, широким дверным проемом и квалифицированным персоналом, обученным работать с людьми с инвалидностью.",
    category: "pharmacy",
    address: "пр. Стачки, 198, Ростов-на-Дону",
    latitude: 47.2195,
    longitude: 39.6724,
    phone: "+7 (863) 222-33-44",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,wide_door,handrails",
    disability_types: "wheelchair,limited_mobility,elderly,stroller",
    rating: 4.1,
    reviews_count: 8
  },
  {
    name: "Ростовский краеведческий музей",
    description: "Музей с лифтом, тактильными экспонатами, аудиогидом и специальными программами для слабовидящих.",
    category: "museum",
    address: "ул. Большая Садовая, 79, Ростов-на-Дону",
    latitude: 47.2276,
    longitude: 39.7452,
    phone: "+7 (863) 263-55-72",
    website: "https://rostovmuseum.ru",
    images: "[]",
    accessibility_tags: "ramp,elevator,tactile_tiles,audio_guide,braille",
    disability_types: "wheelchair,visually_impaired,limited_mobility,cognitive,elderly",
    rating: 4.3,
    reviews_count: 14
  },
  {
    name: "Сбербанк - Центральное отделение",
    description: "Банковское отделение с полной доступностью, включая пандусы, тактильные указатели, электронную очередь.",
    category: "bank",
    address: "ул. Большая Садовая, 30, Ростов-на-Дону",
    latitude: 47.2268,
    longitude: 39.7486,
    phone: "+7 (800) 555-55-50",
    website: "https://sberbank.ru",
    images: "[]",
    accessibility_tags: "ramp,wide_door,tactile_tiles,braille,elevator",
    disability_types: "wheelchair,visually_impaired,limited_mobility,elderly",
    rating: 4.0,
    reviews_count: 7
  },
  {
    name: "Остановка \"Театральная площадь\"",
    description: "Оборудованная остановка общественного транспорта с низкопольными автобусами, тактильной полосой и навесом.",
    category: "transport_stop",
    address: "Театральная площадь, Ростов-на-Дону",
    latitude: 47.2280,
    longitude: 39.7445,
    phone: "",
    website: "",
    images: "[]",
    accessibility_tags: "tactile_tiles,low_floor_transport,bench,ramp",
    disability_types: "wheelchair,visually_impaired,limited_mobility,elderly,stroller",
    rating: 3.9,
    reviews_count: 5
  },
  {
    name: "Ресторан \"Башня\"",
    description: "Ресторан на набережной с доступным входом, просторным залом и туалетом для маломобильных граждан.",
    category: "restaurant",
    address: "ул. Береговая, 29, Ростов-на-Дону",
    latitude: 47.2147,
    longitude: 39.7137,
    phone: "+7 (863) 268-00-00",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,wide_door,elevator,parking_disabled",
    disability_types: "wheelchair,limited_mobility,elderly,stroller",
    rating: 4.4,
    reviews_count: 11
  },
  {
    name: "Левобережный парк",
    description: "Парк на левом берегу Дона с ровными дорожками, скамейками через каждые 100м и пологими спусками.",
    category: "park",
    address: "Левый берег Дона, Ростов-на-Дону",
    latitude: 47.2091,
    longitude: 39.7055,
    phone: "",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,bench,rest_area,simple_navigation,tactile_tiles",
    disability_types: "wheelchair,visually_impaired,limited_mobility,cognitive,elderly,stroller",
    rating: 4.2,
    reviews_count: 16
  },
  {
    name: "Дворец спорта",
    description: "Спортивный комплекс с адаптированными залами, лифтами и специальными программами для людей с ОВЗ.",
    category: "sport",
    address: "пр. Буденновский, 128, Ростов-на-Дону",
    latitude: 47.2425,
    longitude: 39.7190,
    phone: "+7 (863) 245-12-12",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,elevator,wide_door,parking_disabled,handrails",
    disability_types: "wheelchair,limited_mobility,hearing_impaired,elderly",
    rating: 4.1,
    reviews_count: 9
  },
  {
    name: "Библиотека им. Горького",
    description: "Центральная городская библиотека с отделом для слабовидящих, книгами шрифтом Брайля и аудиокнигами.",
    category: "library",
    address: "ул. Пушкинская, 175А, Ростов-на-Дону",
    latitude: 47.2301,
    longitude: 39.7284,
    phone: "+7 (863) 264-85-97",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,elevator,braille,audio_guide,tactile_tiles",
    disability_types: "wheelchair,visually_impaired,limited_mobility,cognitive,elderly",
    rating: 4.5,
    reviews_count: 6
  },
  {
    name: "Магазин \"Перекресток\" - Большая Садовая",
    description: "Супермаркет с широкими проходами, пандусом, специальной парковкой и помощью персонала.",
    category: "shop",
    address: "ул. Большая Садовая, 58, Ростов-на-Дону",
    latitude: 47.2273,
    longitude: 39.7470,
    phone: "+7 (800) 700-50-25",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,wide_door,parking_disabled,simple_navigation",
    disability_types: "wheelchair,limited_mobility,elderly,stroller",
    rating: 4.0,
    reviews_count: 10
  },
  {
    name: "Остановка \"Ворошиловский проспект\"",
    description: "Остановка с тактильной плиткой, информационным табло и низкопольными автобусами.",
    category: "transport_stop",
    address: "пр. Ворошиловский / ул. Большая Садовая, Ростов-на-Дону",
    latitude: 47.2275,
    longitude: 39.7189,
    phone: "",
    website: "",
    images: "[]",
    accessibility_tags: "tactile_tiles,low_floor_transport,bench,vibro_signal",
    disability_types: "wheelchair,visually_impaired,hearing_impaired,limited_mobility,elderly,stroller",
    rating: 3.7,
    reviews_count: 4
  },
  {
    name: "МФЦ Ленинского района",
    description: "Многофункциональный центр с полной безбарьерной средой, электронной очередью, пандусами и помощью сурдопереводчика.",
    category: "government",
    address: "ул. Пушкинская, 176, Ростов-на-Дону",
    latitude: 47.2298,
    longitude: 39.7281,
    phone: "+7 (863) 282-55-55",
    website: "https://mfc61.ru",
    images: "[]",
    accessibility_tags: "ramp,elevator,wide_door,tactile_tiles,vibro_signal,braille,parking_disabled",
    disability_types: "wheelchair,visually_impaired,hearing_impaired,limited_mobility,cognitive,elderly",
    rating: 4.3,
    reviews_count: 20
  },
  {
    name: "Кинотеатр \"Киномакс-Дон\"",
    description: "Кинотеатр в ТЦ с доступным входом, лифтом, местами для колясок и субтитрами на выбранных сеансах.",
    category: "cinema",
    address: "пр. Михаила Нагибина, 32/2, Ростов-на-Дону",
    latitude: 47.2365,
    longitude: 39.7130,
    phone: "+7 (863) 303-10-10",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,elevator,wide_door,subtitles,parking_disabled",
    disability_types: "wheelchair,hearing_impaired,limited_mobility,elderly,stroller",
    rating: 4.0,
    reviews_count: 8
  },
  {
    name: "Центральный рынок",
    description: "Главный рынок города с обустроенными проходами, пандусами и зонами отдыха.",
    category: "shop",
    address: "ул. Станиславского, 62, Ростов-на-Дону",
    latitude: 47.2247,
    longitude: 39.7157,
    phone: "",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,wide_door,bench,rest_area",
    disability_types: "wheelchair,limited_mobility,elderly,stroller",
    rating: 3.6,
    reviews_count: 13
  },
  {
    name: "Набережная реки Дон",
    description: "Благоустроенная набережная с пандусами, скамейками, тактильной навигацией и доступными туалетами.",
    category: "park",
    address: "ул. Береговая, Ростов-на-Дону",
    latitude: 47.2148,
    longitude: 39.7200,
    phone: "",
    website: "",
    images: "[]",
    accessibility_tags: "ramp,tactile_tiles,bench,rest_area,simple_navigation",
    disability_types: "wheelchair,visually_impaired,limited_mobility,cognitive,elderly,stroller",
    rating: 4.6,
    reviews_count: 35
  }
];

export const markers = [
  {
    user_id: 1,
    title: "Пандус у входа в ТЦ Горизонт",
    description: "Удобный пологий пандус с перилами. Ширина достаточна для коляски.",
    latitude: 47.2363,
    longitude: 39.7128,
    marker_type: "building_entrance",
    accessibility_tags: "ramp,handrails",
    photos: "[]",
    votes_up: 12,
    votes_down: 1
  },
  {
    user_id: 1,
    title: "Тактильная плитка на Большой Садовой",
    description: "Участок тротуара с хорошей тактильной плиткой от пр. Ворошиловский до ул. Семашко.",
    latitude: 47.2270,
    longitude: 39.7350,
    marker_type: "sidewalk",
    accessibility_tags: "tactile_tiles",
    photos: "[]",
    votes_up: 8,
    votes_down: 0
  },
  {
    user_id: 1,
    title: "Опасный бордюр у перехода",
    description: "Высокий бордюр без съезда на пересечении Ворошиловского и Большой Садовой. Сложно проехать на коляске.",
    latitude: 47.2273,
    longitude: 39.7188,
    marker_type: "crossing",
    accessibility_tags: "wide_door",
    photos: "[]",
    votes_up: 15,
    votes_down: 2
  },
  {
    user_id: 1,
    title: "Доступный туалет в Парке Горького",
    description: "Оборудованный туалет для маломобильных граждан. Широкая дверь, поручни.",
    latitude: 47.2265,
    longitude: 39.7480,
    marker_type: "facility",
    accessibility_tags: "wide_door,handrails",
    photos: "[]",
    votes_up: 20,
    votes_down: 3
  },
  {
    user_id: 1,
    title: "Низкопольный вход в автобус маршрута 3",
    description: "На маршруте 3 ходят низкопольные автобусы. Удобная посадка для колясочников.",
    latitude: 47.2281,
    longitude: 39.7446,
    marker_type: "transport",
    accessibility_tags: "low_floor_transport,ramp",
    photos: "[]",
    votes_up: 6,
    votes_down: 1
  }
];

export const reviews = [
  {
    user_id: 1,
    place_id: 1,
    marker_id: null,
    text: "Отличный торговый центр! Все входы оборудованы пандусами, есть лифты на все этажи. Парковка для инвалидов прямо у входа.",
    rating: 5,
    photos: "[]"
  },
  {
    user_id: 1,
    place_id: 2,
    marker_id: null,
    text: "Хороший подъем у входа, но узкий проход в зале. Субтитры есть не на всех сеансах - уточняйте.",
    rating: 4,
    photos: "[]"
  },
  {
    user_id: 1,
    place_id: 5,
    marker_id: null,
    text: "Прекрасный театр! Места для колясочников в партере, есть индукционная петля. Персонал очень внимательный.",
    rating: 5,
    photos: "[]"
  },
  {
    user_id: 1,
    place_id: 6,
    marker_id: null,
    text: "Парк хорошо обустроен, дорожки ровные. Скамейки есть, но не все с подлокотниками.",
    rating: 4,
    photos: "[]"
  },
  {
    user_id: 1,
    place_id: 20,
    marker_id: null,
    text: "Набережная очень красивая и доступная. Единственное - в дождь бывает скользко на плитке.",
    rating: 4,
    photos: "[]"
  }
];

export const routes = [
  {
    user_id: 1,
    name: "Прогулка по центру (доступный маршрут)",
    description: "Доступный маршрут по центру Ростова для колясочников. Все точки с пандусами и широкими проходами.",
    disability_types: "wheelchair,limited_mobility",
    total_distance_km: 3.2,
    total_duration_hours: 1.5,
    points: JSON.stringify([
      { name: "Парк Горького", latitude: 47.2264, longitude: 39.7478, order: 0, accessibility_tags: "ramp,bench" },
      { name: "Кафе Тихий Дон", latitude: 47.2271, longitude: 39.7463, order: 1, accessibility_tags: "ramp,wide_door" },
      { name: "Ростовский краеведческий музей", latitude: 47.2276, longitude: 39.7452, order: 2, accessibility_tags: "ramp,elevator" },
      { name: "Набережная реки Дон", latitude: 47.2148, longitude: 39.7200, order: 3, accessibility_tags: "ramp,bench" }
    ])
  }
];
